---
title: "Quarto Presentations"
subtitle: "Create beautiful interactive slide decks with Reveal.js"
author: Shafayet Khan Shafee
date: last-modified
format:
  revealjs: 
    slide-number: true
    logo: images/quarto.png
    footer: <https://quarto.org>
    header: |
      Quarto Presentations with beautiful slide decks made by RevealJs
    header-logo: images/reveal_logo.svg
filters:
  - reveal-header
execute: 
  eval: false
  echo: true
---

## Hello, There

This presentation will show you some examples of what you can do with Quarto and [Reveal.js](https://revealjs.com) along with header logo and header text, including:

-   Presenting code and LaTeX equations
-   Including computations in slide output
-   Image, video, and iframe backgrounds
-   Fancy transitions and animations
-   Printing to PDF

...and much more


## Executable Code

```{r}
#| echo: true
#| fig-width: 10
#| fig-height: 4.5

library(ggplot2)
ggplot(mtcars, aes(hp, mpg, color = am)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method = "loess")
```

::: footer
Learn more: [Executable Code](https://quarto.org/docs/presentations/revealjs/#executable-code)
:::


## Slide Backgrounds {background="#43464B"}

This slide is created using the `background` attribute (`background="#43464B"}`) and as you can see that header text color is different (difference is trivial though) than before.

if you want you can change the color of the header text for slides with `background` attribute using css class `.inverse-header`. For example,

~~~
.inverse-header {
  color: #c1c1c1 !important;
}
~~~

Here using `!important` is important :p.

::: footer
Learn more: [Slide Backgrounds](https://quarto.org/docs/presentations/revealjs/#color-backgrounds)
:::
